In [67]:
import matplotlib.pyplot as plt
import numpy as np
import sys
sys.path.append('/home/matt/readout/host/')
import ali_offline_demod as dm
import imp
imp.reload(dm)
import glob
import pickle
from scipy import spatial

In [80]:
#ASU numbering
#south line
GHz150_lines = [11,12,8,7] 
GHz95_lines = [10,9] 

In [81]:
data_directory = 'name_of_directory' #it knows the parent directory, so you just need the 
                                     #specific directory name

datafiles = glob.glob('./[!bias][!ipynb]*')
print(datafiles)

fig_95_Cold, ax_95_Cold = plt.subplots(1, figsize=(14, 10))
fig_95_Warm, ax_95_Warm = plt.subplots(1, figsize=(14, 10))
fig_150_Cold, ax_150_Cold = plt.subplots(1, figsize=(14, 10))
fig_150_Warm, ax_150_Warm = plt.subplots(1, figsize=(14, 10))
    
for pickle_i in datafiles:
    plt.figure()
    print(pickle_i)
    temp = pickle_i.split('_')[-1].split('.')[0]
    ASU_BL = int(pickle_i.split('_')[-2].split('L')[1])
    
    print(temp, ASU_BL)
    
    with open(pickle_i, 'rb') as f:
        data_i = pickle.load(f) 
    
    if temp == "Cold" and np.in1d(ASU_BL, GHz150_lines)[0]:
        for ch in range(len(data_i['Vtes'])):
            ax_150_Cold.plot(data_i['Vtes'][ch],data_i['Ites'][ch],'b',alpha=0.1)
            
    elif temp == "Warm" and np.in1d(ASU_BL, GHz150_lines)[0]:
        for ch in range(len(data_i['Vtes'])):
            ax_150_Warm.plot(data_i['Vtes'][ch],data_i['Ites'][ch],'b',alpha=0.1)
            
    elif temp == "Cold" and np.in1d(ASU_BL, GHz95_lines)[0]:
        for ch in range(len(data_i['Vtes'])):
            ax_95_Cold.plot(data_i['Vtes'][ch],data_i['Ites'][ch],'r',alpha=0.1)
            
    elif temp == "Warm" and np.in1d(ASU_BL, GHz95_lines)[0]:
        for ch in range(len(data_i['Vtes'])):
            ax_95_Warm.plot(data_i['Vtes'][ch],data_i['Ites'][ch],'r',alpha=0.1)
            
ax_95_Cold.set_title('95 GHz TESes; 77 K Load',fontsize=20)
ax_95_Cold.set_ylabel('$I_{TES}$ (mA)',fontsize=18)
ax_95_Cold.set_xlabel('$V_{TES}$ (μV)',fontsize=18)
ax_95_Cold.tick_params(axis='both', which='major', labelsize=16)

ax_95_Warm.set_title('95 GHz TESes; 300 K Load',fontsize=20)
ax_95_Warm.set_ylabel('$I_{TES}$ (mA)',fontsize=18)
ax_95_Warm.set_xlabel('$V_{TES}$ (μV)',fontsize=18)
ax_95_Warm.tick_params(axis='both', which='major', labelsize=16)

ax_150_Cold.set_title('150 GHz TESes; 77 K Load',fontsize=20)
ax_150_Cold.set_ylabel('$I_{TES}$ (mA)',fontsize=18)
ax_150_Cold.set_xlabel('$V_{TES}$ (μV)',fontsize=18)
ax_150_Cold.tick_params(axis='both', which='major', labelsize=16)

ax_150_Warm.set_title('150 GHz TESes; 300 K Load',fontsize=20)
ax_150_Warm.set_ylabel('$I_{TES}$ (mA)',fontsize=18)
ax_150_Warm.set_xlabel('$V_{TES}$ (μV)',fontsize=18)
ax_150_Warm.tick_params(axis='both', which='major', labelsize=16)


['./20240213_results_4750MHz_BL8_Warm.pkl', './20240213_results_4250MHz_BL11_Cold.pkl', './20240213_results_4250MHz_BL10_Cold.pkl', './20240213_results_4750MHz_BL7_Cold.pkl', './20240213_results_6750MHz_BL12_Warm.pkl', './20240213_results_5250MHz_BL9_Cold.pkl', './20240213_results_4750MHz_BL7_Warm.pkl', './20240213_results_5750MHz_BL8_Warm.pkl', './20240213_results_6250MHz_BL8_Warm.pkl', './20240213_results_4250MHz_BL11_Warm.pkl', './20240213_results_6750MHz_BL12_Cold.pkl', './20240213_results_5750MHz_BL11_Cold.pkl', './20240213_results_4750MHz_BL9_Warm.pkl', './20240213_results_5250MHz_BL12_Warm.pkl', './20240213_results_4750MHz_BL9_Cold.pkl', './20240213_results_5750MHz_BL8_Cold.pkl', './20240213_results_4750MHz_BL8_Cold.pkl', './20240213_results_5250MHz_BL12_Cold.pkl', './20240213_results_6250MHz_BL8_Cold.pkl', './20240213_results_4250MHz_BL10_Warm.pkl', './20240213_results_4250MHz_BL9_Cold.pkl', './20240213_results_4750MHz_BL11_Cold.pkl', './20240213_results_5250MHz_BL7_Warm.pkl', 

/tmp/ipykernel_156540/946522514.py:13: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  plt.figure()


./20240213_results_4750MHz_BL9_Cold.pkl
Cold 9
./20240213_results_5750MHz_BL8_Cold.pkl
Cold 8
./20240213_results_4750MHz_BL8_Cold.pkl
Cold 8
./20240213_results_5250MHz_BL12_Cold.pkl
Cold 12
./20240213_results_6250MHz_BL8_Cold.pkl
Cold 8
./20240213_results_4250MHz_BL10_Warm.pkl
Warm 10
./20240213_results_4250MHz_BL9_Cold.pkl
Cold 9
./20240213_results_4750MHz_BL11_Cold.pkl
Cold 11
./20240213_results_5250MHz_BL7_Warm.pkl
Warm 7
./20240213_results_5750MHz_BL11_Warm.pkl
Warm 11
./20240213_results_5250MHz_BL9_Warm.pkl
Warm 9
./20240213_results_4250MHz_BL9_Warm.pkl
Warm 9
./20240213_results_4750MHz_BL11_Warm.pkl
Warm 11
./20240213_results_5250MHz_BL7_Cold.pkl
Cold 7


In [106]:
data_directory = 'name_of_directory' #it knows the parent directory, so you just need the 
                                     #specific directory name

datafiles = glob.glob('./[!bias][!ipynb]*')
print(datafiles)

fig_95_Cold, ax_95_Cold = plt.subplots(1, figsize=(14, 10))
fig_95_Warm, ax_95_Warm = plt.subplots(1, figsize=(14, 10))
fig_150_Cold, ax_150_Cold = plt.subplots(1, figsize=(14, 10))
fig_150_Warm, ax_150_Warm = plt.subplots(1, figsize=(14, 10))
    
for pickle_i in datafiles:
    plt.figure()
    print(pickle_i)
    temp = pickle_i.split('_')[-1].split('.')[0]
    ASU_BL = int(pickle_i.split('_')[-2].split('L')[1])
    
    print(temp, ASU_BL)
    
    with open(pickle_i, 'rb') as f:
        data_i = pickle.load(f) 
    
    if temp == "Cold" and np.in1d(ASU_BL, GHz150_lines)[0]:
        for ch in range(len(data_i['Vtes'])):
            ax_150_Cold.plot(data_i['Ibias'],data_i['bps'][ch],'b',alpha=0.1)
            
    elif temp == "Warm" and np.in1d(ASU_BL, GHz150_lines)[0]:
        for ch in range(len(data_i['Vtes'])):
            ax_150_Warm.plot(data_i['Ibias'],data_i['bps'][ch],'b',alpha=0.1)
            
    elif temp == "Cold" and np.in1d(ASU_BL, GHz95_lines)[0]:
        for ch in range(len(data_i['Vtes'])):
            ax_95_Cold.plot(data_i['Ibias'],data_i['bps'][ch],'r',alpha=0.1)
            
    elif temp == "Warm" and np.in1d(ASU_BL, GHz95_lines)[0]:
        for ch in range(len(data_i['Vtes'])):
            ax_95_Warm.plot(data_i['Ibias'],data_i['bps'][ch],'r',alpha=0.1)
            
ax_95_Cold.set_title('95 GHz TESes; 77 K Load',fontsize=20)
ax_95_Cold.set_ylabel('$I_{TES}$ (mA)',fontsize=18)
ax_95_Cold.set_xlabel('$V_{TES}$ (μV)',fontsize=18)
ax_95_Cold.tick_params(axis='both', which='major', labelsize=16)
ax_95_Cold.ylim([0,1.1])

ax_95_Warm.set_title('95 GHz TESes; 300 K Load',fontsize=20)
ax_95_Warm.set_ylabel('$I_{TES}$ (mA)',fontsize=18)
ax_95_Warm.set_xlabel('$V_{TES}$ (μV)',fontsize=18)
ax_95_Warm.tick_params(axis='both', which='major', labelsize=16)
ax_95_Warm.ylim([0,1.1])

ax_150_Cold.set_title('150 GHz TESes; 77 K Load',fontsize=20)
ax_150_Cold.set_ylabel('$I_{TES}$ (mA)',fontsize=18)
ax_150_Cold.set_xlabel('$V_{TES}$ (μV)',fontsize=18)
ax_150_Cold.tick_params(axis='both', which='major', labelsize=16)
ax_150_Cold.ylim([0,1.1])

ax_150_Warm.set_title('150 GHz TESes; 300 K Load',fontsize=20)
ax_150_Warm.set_ylabel('$I_{TES}$ (mA)',fontsize=18)
ax_150_Warm.set_xlabel('$V_{TES}$ (μV)',fontsize=18)
ax_150_Warm.tick_params(axis='both', which='major', labelsize=16)
ax_150_Warm.ylim([0,1.1])

['./20240213_results_4750MHz_BL8_Warm.pkl', './20240213_results_4250MHz_BL11_Cold.pkl', './20240213_results_4250MHz_BL10_Cold.pkl', './20240213_results_4750MHz_BL7_Cold.pkl', './20240213_results_6750MHz_BL12_Warm.pkl', './20240213_results_5250MHz_BL9_Cold.pkl', './20240213_results_4750MHz_BL7_Warm.pkl', './20240213_results_5750MHz_BL8_Warm.pkl', './20240213_results_6250MHz_BL8_Warm.pkl', './20240213_results_4250MHz_BL11_Warm.pkl', './20240213_results_6750MHz_BL12_Cold.pkl', './20240213_results_5750MHz_BL11_Cold.pkl', './20240213_results_4750MHz_BL9_Warm.pkl', './20240213_results_5250MHz_BL12_Warm.pkl', './20240213_results_4750MHz_BL9_Cold.pkl', './20240213_results_5750MHz_BL8_Cold.pkl', './20240213_results_4750MHz_BL8_Cold.pkl', './20240213_results_5250MHz_BL12_Cold.pkl', './20240213_results_6250MHz_BL8_Cold.pkl', './20240213_results_4250MHz_BL10_Warm.pkl', './20240213_results_4250MHz_BL9_Cold.pkl', './20240213_results_4750MHz_BL11_Cold.pkl', './20240213_results_5250MHz_BL7_Warm.pkl', 

/tmp/ipykernel_156540/2271432728.py:13: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  plt.figure()


./20240213_results_5250MHz_BL12_Cold.pkl
Cold 12
./20240213_results_6250MHz_BL8_Cold.pkl
Cold 8
./20240213_results_4250MHz_BL10_Warm.pkl
Warm 10
./20240213_results_4250MHz_BL9_Cold.pkl
Cold 9
./20240213_results_4750MHz_BL11_Cold.pkl
Cold 11
./20240213_results_5250MHz_BL7_Warm.pkl
Warm 7
./20240213_results_5750MHz_BL11_Warm.pkl
Warm 11
./20240213_results_5250MHz_BL9_Warm.pkl
Warm 9
./20240213_results_4250MHz_BL9_Warm.pkl
Warm 9
./20240213_results_4750MHz_BL11_Warm.pkl
Warm 11
./20240213_results_5250MHz_BL7_Cold.pkl
Cold 7


AttributeError: 'AxesSubplot' object has no attribute 'ylim'

In [82]:
for i,pickle_i in enumerate(datafiles):
    print(pickle_i)
    temp = pickle_i.split('_')[-1].split('.')[0]
    ASU_BL = int(pickle_i.split('_')[-2].split('L')[1])
    print (ASU_BL, i)

./20240213_results_4750MHz_BL8_Warm.pkl
8 0
./20240213_results_4250MHz_BL11_Cold.pkl
11 1
./20240213_results_4250MHz_BL10_Cold.pkl
10 2
./20240213_results_4750MHz_BL7_Cold.pkl
7 3
./20240213_results_6750MHz_BL12_Warm.pkl
12 4
./20240213_results_5250MHz_BL9_Cold.pkl
9 5
./20240213_results_4750MHz_BL7_Warm.pkl
7 6
./20240213_results_5750MHz_BL8_Warm.pkl
8 7
./20240213_results_6250MHz_BL8_Warm.pkl
8 8
./20240213_results_4250MHz_BL11_Warm.pkl
11 9
./20240213_results_6750MHz_BL12_Cold.pkl
12 10
./20240213_results_5750MHz_BL11_Cold.pkl
11 11
./20240213_results_4750MHz_BL9_Warm.pkl
9 12
./20240213_results_5250MHz_BL12_Warm.pkl
12 13
./20240213_results_4750MHz_BL9_Cold.pkl
9 14
./20240213_results_5750MHz_BL8_Cold.pkl
8 15
./20240213_results_4750MHz_BL8_Cold.pkl
8 16
./20240213_results_5250MHz_BL12_Cold.pkl
12 17
./20240213_results_6250MHz_BL8_Cold.pkl
8 18
./20240213_results_4250MHz_BL10_Warm.pkl
10 19
./20240213_results_4250MHz_BL9_Cold.pkl
9 20
./20240213_results_4750MHz_BL11_Cold.pkl
11 21


In [83]:
with open(datafiles[0], 'rb') as f:
        data_0 = pickle.load(f) 
with open(datafiles[16], 'rb') as f:
        data_16 = pickle.load(f) 


In [95]:
freq0=data_0['time series data']['channel freqs']
freq16=data_16['time series data']['channel freqs']

In [84]:
freq0_ind=np.vstack((freq0,np.arange(freq0.shape[0])))
freq0_ind=np.vstack((freq0_ind,np.zeros(freq0.shape[0])))
freq16_ind=np.vstack((freq16,np.arange(freq16.shape[0])))
freq16_ind=np.vstack((freq16_ind,np.ones(freq16.shape[0])))
freqs_all=np.vstack((freq0_ind.T,freq16_ind.T))

In [91]:
tree = spatial.cKDTree(freqs_all[:,0:1])
idups_raw=tree.query_ball_tree(tree,1e5)
idups_ids=[freqs_all[x,1].astype(int) for x in idups_raw]

/tmp/ipykernel_154536/803759362.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  tree = spatial.cKDTree(freqs_all[:,0:1])
/tmp/ipykernel_154536/803759362.py:3: ComplexWarning: Casting complex values to real discards the imaginary part
  idups_ids=[freqs_all[x,1].astype(int) for x in idups_raw]


In [92]:
idups_ids

[array([0]),
 array([1, 0]),
 array([2, 1]),
 array([3, 2]),
 array([4, 3]),
 array([5, 4]),
 array([6, 5]),
 array([7, 6]),
 array([8, 7]),
 array([9, 8]),
 array([10,  9]),
 array([11, 10]),
 array([12, 11]),
 array([13, 12]),
 array([14, 13]),
 array([15, 14]),
 array([16, 15]),
 array([17, 16]),
 array([18, 17]),
 array([19, 18]),
 array([20, 19]),
 array([21, 20]),
 array([22, 21]),
 array([23, 22]),
 array([24, 23]),
 array([25, 24]),
 array([26, 25]),
 array([27, 26]),
 array([28, 27]),
 array([29, 28]),
 array([30, 29]),
 array([31, 30]),
 array([32, 31]),
 array([33, 32]),
 array([34, 33]),
 array([35, 34]),
 array([36, 35]),
 array([37, 36]),
 array([38, 37]),
 array([39, 38]),
 array([40, 39]),
 array([41, 40]),
 array([42, 41]),
 array([43, 42]),
 array([44, 43]),
 array([45, 44]),
 array([46, 45]),
 array([47, 46]),
 array([48, 47]),
 array([49, 48]),
 array([50, 49]),
 array([51, 50]),
 array([52, 51]),
 array([53, 52]),
 array([54, 53]),
 array([55, 54]),
 array([56, 55]

In [98]:
def match_freqs(f1,f2,dist=1e5):
    f1_ind=np.vstack((f1,np.arange(f1.shape[0])))
    f1_ind=np.vstack((f1_ind,np.ones(f1.shape[0])*0))
    f2_ind=np.vstack((f2,np.arange(f2.shape[0])))
    f2_ind=np.vstack((f2_ind,np.ones(f2.shape[0])*1))
    fall=np.vstack((f1_ind.T,f2_ind.T))
    tree = spatial.cKDTree(fall[:,0:1])
    idups_raw=tree.query_ball_tree(tree,dist)
    idups_redu=[]
    for match in idups_raw:
        if len(match)!=2: continue
        else: 
            if int(fall[match[0],2])==0 and int(fall[match[1],2])==1:
                idups_redu.append(match)
    idups_ids=[fall[x,1].astype(int) for x in idups_redu]
    return idups_ids
    
    

In [124]:
pbias_warm=dm.get_pbias(data_0,0.9)
pbias_cold=dm.get_pbias(data_16,0.9)

#print(data_0['bps'])
#print(data_0['bps'].shape)

#print(pbias_warm.shape)

#print(pbias_warm)
plt.figure(figsize=(14,10))
plt.hist(pbias_warm, label='300 K')
plt.hist(pbias_cold, alpha=0.5, label='77 K')
plt.xlabel('N', fontsize=18)
plt.ylabel('$P_{sat}$ (pW)', fontsize=18)
plt.legend(fontsize=18)
plt.tick_params(axis='both', which='major', labelsize=16)

In [126]:
#print (match_freqs(freq0,freq16))

matches = match_freqs(freq0,freq16)
#print(matches)

pbias_difference = np.array([])
for match in matches:
    if ~np.isnan(pbias_warm[match[0]]) and ~np.isnan(pbias_cold[match[1]]):
        pbias_difference = np.append(pbias_difference, pbias_warm[match[0]] - pbias_cold[match[1]]) 
    
plt.figure(figsize=(14,10))   
plt.hist(pbias_difference)
plt.ylabel('N',fontsize=18)
plt.xlabel('Δ$P_{sat}$ (pW)',fontsize=18)
plt.tick_params(axis='both', which='major', labelsize=16)
    
    #plt.figure()
    #plt.plot(data_0['Vtes'][match[0]], data_0['Ites'][match[0]],'-')
    #plt.plot(data_16['Vtes'][match[1]], data_16['Ites'][match[1]],'-')
    

/tmp/ipykernel_156540/63498383.py:7: ComplexWarning: Casting complex values to real discards the imaginary part
  tree = spatial.cKDTree(fall[:,0:1])
/tmp/ipykernel_156540/63498383.py:13: ComplexWarning: Casting complex values to real discards the imaginary part
  if int(fall[match[0],2])==0 and int(fall[match[1],2])==1:
/tmp/ipykernel_156540/63498383.py:15: ComplexWarning: Casting complex values to real discards the imaginary part
  idups_ids=[fall[x,1].astype(int) for x in idups_redu]


In [131]:
#print (match_freqs(freq0,freq16))
#pW/K



matches = match_freqs(freq0,freq16)
#print(matches)

delta_T = 77-300


pbias_difference = np.array([])
for match in matches:
    if ~np.isnan(pbias_warm[match[0]]) and ~np.isnan(pbias_cold[match[1]]):
        pbias_difference = np.append(pbias_difference, pbias_warm[match[0]] - pbias_cold[match[1]]) 
    
plt.figure(figsize=(14,10))   
plt.hist(pbias_difference/delta_T)
plt.ylabel('N',fontsize=18)
plt.xlabel('Δ$P_{sat}$/Δ$T$ (pW/Κ)',fontsize=18)
plt.tick_params(axis='both', which='major', labelsize=16)
    
    #plt.figure()
    #plt.plot(data_0['Vtes'][match[0]], data_0['Ites'][match[0]],'-')
    #plt.plot(data_16['Vtes'][match[1]], data_16['Ites'][match[1]],'-')
    

/tmp/ipykernel_156540/63498383.py:7: ComplexWarning: Casting complex values to real discards the imaginary part
  tree = spatial.cKDTree(fall[:,0:1])
/tmp/ipykernel_156540/63498383.py:13: ComplexWarning: Casting complex values to real discards the imaginary part
  if int(fall[match[0],2])==0 and int(fall[match[1],2])==1:
/tmp/ipykernel_156540/63498383.py:15: ComplexWarning: Casting complex values to real discards the imaginary part
  idups_ids=[fall[x,1].astype(int) for x in idups_redu]


In [156]:
#pW/K full dataset

#warm_datafiles = glob.glob('./[!bias][!ipynb]*Warm*')
#cold_datafiles = glob.glob('./[!bias][!ipynb]*Cold*')

#print(cold_datafiles)

delta_T = 77-300

pbias_difference = np.array([])

for BL in [7,8,9,10,11,12]:
    for freq in [4250, 4750, 5250, 5750, 6250, 6750]:
        warm_datafile = glob.glob(f'./[!csv][!ipynb]*{freq}*{BL}*Warm*')
        cold_datafile = glob.glob(f'./[!csv][!ipynb]*{freq}*{BL}*Cold*')
        
        

        
        if len(warm_datafile) != 0 and len(cold_datafile) != 0:
            
            #print(warm_datafile)
            #print(cold_datafile)
            
            with open(warm_datafile[0], 'rb') as f:
                warm_data = pickle.load(f) 
            with open(cold_datafile[0], 'rb') as f:
                cold_data = pickle.load(f) 
             
            pbias_warm=dm.get_pbias(warm_data,0.9)
            pbias_cold=dm.get_pbias(cold_data,0.9)
            
            freq_pairs = match_freqs(warm_data['time series data']['channel freqs'],cold_data['time series data']['channel freqs'],dist=1e5)
            #print(freq_pairs)
                     
            for match in freq_pairs:
                if ~np.isnan(pbias_warm[match[0]]) and ~np.isnan(pbias_cold[match[1]]):
                    pbias_difference = np.append(pbias_difference, pbias_warm[match[0]] - pbias_cold[match[1]]) 
                    

fig_full, ax_full = plt.subplots(1, figsize=(14,10))
fig_limited, ax_limited = plt.subplots(1, figsize=(14,10))
   
ax_full.hist(pbias_difference/delta_T,bins=100)
ax_full.set_ylabel('N',fontsize=18)
ax_full.set_xlabel('Δ$P_{sat}$/Δ$T$ (pW/Κ)',fontsize=18)
ax_full.tick_params(axis='both', which='major', labelsize=16)
print(np.average(pbias_difference/delta_T))

ax_limited.hist(pbias_difference/delta_T,bins=100)
ax_limited.set_ylabel('N',fontsize=18)
ax_limited.set_xlabel('Δ$P_{sat}$/Δ$T$ (pW/Κ)',fontsize=18)
ax_limited.tick_params(axis='both', which='major', labelsize=16)
ax_limited.set_xlim([-1,1])
print(np.average(pbias_difference/delta_T))

/tmp/ipykernel_156540/63498383.py:7: ComplexWarning: Casting complex values to real discards the imaginary part
  tree = spatial.cKDTree(fall[:,0:1])
/tmp/ipykernel_156540/63498383.py:13: ComplexWarning: Casting complex values to real discards the imaginary part
  if int(fall[match[0],2])==0 and int(fall[match[1],2])==1:
/tmp/ipykernel_156540/63498383.py:15: ComplexWarning: Casting complex values to real discards the imaginary part
  idups_ids=[fall[x,1].astype(int) for x in idups_redu]


0.13511132950450644
0.13511132950450644


In [123]:
data_directory = 'name_of_directory' #it knows the parent directory, so you just need the 
                                     #specific directory name

datafiles = glob.glob('./[!bias][!ipynb]*')
print(datafiles)

fig_95, ax_95 = plt.subplots(1, figsize=(14, 10))
fig_150, ax_150 = plt.subplots(1, figsize=(14, 10))

cold_150 = 0
warm_150 = 0
cold_95 = 0
warm_95 = 0

for pickle_i in datafiles:
    print(pickle_i)
    temp = pickle_i.split('_')[-1].split('.')[0]
    ASU_BL = int(pickle_i.split('_')[-2].split('L')[1])
    
    print(temp, ASU_BL)
    
    with open(pickle_i, 'rb') as f:
        data_i = pickle.load(f) 
    
    if temp == "Cold" and np.in1d(ASU_BL, GHz150_lines)[0]:
        continue
        for ch in range(len(data_i['Vtes'])):
            if cold_150 == 0:
                ax_150.plot(data_i['Ibias'],data_i['bps'][ch]*100,'b',alpha=0.01,label = '77 K')
                cold_150 += 1
            else:
                ax_150.plot(data_i['Ibias'],data_i['bps'][ch]*100,'b',alpha=0.1)
        
            
    elif temp == "Warm" and np.in1d(ASU_BL, GHz150_lines)[0]:
        for ch in range(len(data_i['Vtes'])):
            if warm_150 == 0:
                ax_150.plot(data_i['Ibias'],data_i['bps'][ch]*100,'b',alpha=0.01,label = '300 K')
                warm_150 += 1
            else:
                ax_150.plot(data_i['Ibias'],data_i['bps'][ch]*100,'b',alpha=0.1)
        
        
    elif temp == "Cold" and np.in1d(ASU_BL, GHz95_lines)[0]:
        continue
        for ch in range(len(data_i['Vtes'])):
            if cold_95 == 0:
                ax_95.plot(data_i['Ibias'],data_i['bps'][ch]*100,'b',alpha=0.01,label = '77 K')
                cold_95 += 1
            else:
                ax_95.plot(data_i['Ibias'],data_i['bps'][ch]*100,'b',alpha=0.01)
        
            
    elif temp == "Warm" and np.in1d(ASU_BL, GHz95_lines)[0]:
        for ch in range(len(data_i['Vtes'])):
            if warm_95 == 0:
                ax_95.plot(data_i['Ibias'],data_i['bps'][ch]*100,'r',alpha=0.01,label = '300 K')
                warm_95 += 1
            else:
                ax_95.plot(data_i['Ibias'],data_i['bps'][ch]*100,'r',alpha=0.1)
        
        
ax_95.set_title('95 GHz TESes',fontsize=20)
ax_95.set_xlabel('$I_{bias}$ (mA)',fontsize=18)
ax_95.set_ylabel('$\%(R_{n,Al}$',fontsize=18)
#ax_95.legend(fontsize=18)
ax_95.tick_params(axis='both', which='major', labelsize=16)
ax_95.set_ylim([0,101])

ax_150.set_title('150 GHz TESes',fontsize=20)
ax_150.set_xlabel('$I_{bias}$ (mA)',fontsize=18)
ax_150.set_ylabel('$\%(R_{n,Al})$',fontsize=18)
#ax_150.legend(fontsize=18)
ax_150.tick_params(axis='both', which='major', labelsize=16)
ax_150.set_ylim([0,101])


['./20240213_results_4750MHz_BL8_Warm.pkl', './20240213_results_4250MHz_BL11_Cold.pkl', './20240213_results_4250MHz_BL10_Cold.pkl', './20240213_results_4750MHz_BL7_Cold.pkl', './20240213_results_6750MHz_BL12_Warm.pkl', './20240213_results_5250MHz_BL9_Cold.pkl', './20240213_results_4750MHz_BL7_Warm.pkl', './20240213_results_5750MHz_BL8_Warm.pkl', './20240213_results_6250MHz_BL8_Warm.pkl', './20240213_results_4250MHz_BL11_Warm.pkl', './20240213_results_6750MHz_BL12_Cold.pkl', './20240213_results_5750MHz_BL11_Cold.pkl', './20240213_results_4750MHz_BL9_Warm.pkl', './20240213_results_5250MHz_BL12_Warm.pkl', './20240213_results_4750MHz_BL9_Cold.pkl', './20240213_results_5750MHz_BL8_Cold.pkl', './20240213_results_4750MHz_BL8_Cold.pkl', './20240213_results_5250MHz_BL12_Cold.pkl', './20240213_results_6250MHz_BL8_Cold.pkl', './20240213_results_4250MHz_BL10_Warm.pkl', './20240213_results_4250MHz_BL9_Cold.pkl', './20240213_results_4750MHz_BL11_Cold.pkl', './20240213_results_5250MHz_BL7_Warm.pkl', 

(0.0, 101.0)

In [74]:
#data_file = 'ts_toneinit_fcenter_4250.0_20240220142604_t_20240220150809.hd5'

data_file ='ts_toneinit_fcenter_4250.0_20240215160613_t_20240215180615.hd5'
result = dm.full_demod_process(data_file, f_sawtooth = 15)

%matplotlib qt

plt.figure(figsize=(14,10))

for ch in np.arange(1,10,1):#range(len(result['demod data'])):#[1]:#np.arange(0,50,1):#range(len(result_ts['demod data'])):
    plt.plot(result['demod t'], result['demod data'][ch],'-')
    
plt.xlabel('t (s)',fontsize=18)
plt.ylabel('$N(\Phi_0)$',fontsize=18)
plt.tick_params(axis='both', which='major', labelsize=16)


    #plt.plot(result['demod t'], result_old_demod['demod data'][ch],'-',c='b')

looking for delay region
start = 4018292062.5000005
stop = 4028312570.3125005
3.2332023985618257
n_phi0: 3.2332023985618257


  0%|          | 0/230 [00:00<?, ?it/s]

In [50]:
%matplotlib qt
for ch in range(0,30):#range(len(result['demod data'])):#[1]:#np.arange(0,50,1):#range(len(result_ts['demod data'])):
    plt.plot(result['demod t'], result['demod data'][ch],'-',c='r',label='vector')
    plt.plot(result['demod t'], result_old_demod['demod data'][ch],'-',c='b', label='no vec')



In [60]:
data_file = 'ts_toneinit_fcenter_4250.0_20240220164846_t_20240220165737.hd5'

#data_file ='ts_toneinit_fcenter_4250.0_20240215160613_t_20240215180615.hd5'
result_ns = dm.full_demod_process(data_file, f_sawtooth = 15)

%matplotlib qt
for ch in range(len(result['demod data'])):#[1]:#np.arange(0,50,1):#range(len(result_ts['demod data'])):
    plt.plot(result_ns['demod t'], result_ns['demod data'][ch],'-',alpha=0.3)

looking for delay region
start = 4027774640.6250954
stop = 4037795148.4375954
3.2202166470413514
n_phi0: 3.2202166470413514


  0%|          | 0/233 [00:00<?, ?it/s]

In [49]:
%matplotlib qt
for ch in range(200,230):#range(len(result['demod data'])):#[1]:#np.arange(0,50,1):#range(len(result_ts['demod data'])):
    plt.plot(result_ns['demod t'], result_ns['demod data'][ch],'-',c='r',alpha=0.2)

In [48]:
result_ns['demod data'].shape

(234, 164)